spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    dricer-class-name: org.h2.Driver

  hpa:
    hibernate:
      ddl-auto: create // applicateion 실행 시점에서 table 재생성
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug